In [13]:
def main():

    import PIL
    from PIL import Image
    import os
    import fnmatch
    import numpy as np
    import matplotlib.pylab as plt
    %matplotlib inline

    def plti(im, h=5, **kwargs):
    
        y = im.shape[0]
        x = im.shape[1]
        w = (y/x) * h
        plt.figure(figsize=(w,h))
        plt.imshow(im,interpolation='none', **kwargs)
        plt.axis("off")

    master_array = np.zeros([20,200,200,3])
    print("Shape of master array was" + str(master_array.shape))
    print("Values of Master Array before conversion were" + str(master_array))

    rootDir = 'photos'
    for dirName, subdirList, fileList in os.walk(rootDir):
        print('Found directory: %s' % dirName)

    for fname in fileList:
        if fnmatch.fnmatch(fname, '*.jpg'):
            print('Found JPG image: %s' % fname)
   
    for fname in fileList:
        img = Image.open(str(rootDir + '/' + fname))
        img = img.resize((200, 200), Image.ANTIALIAS)
        img_array = np.array(img)
        master_array[::] = img_array[::]

    print("Shape of master array is" + str(master_array.shape))
    print("Values of Master Array after adding images are" + str(master_array))
     
main()

Shape of master array was(20, 200, 200, 3)
Values of Master Array before conversion were[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 